# Generated by Django 6.0.6 on 2026-07-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "track_equity",
                    models.BooleanField(
                        default=False,
                        help_text="Fetch the underlying's own candles (equity/index)",
                    ),
                ),
                ("track_futures", models.BooleanField(default=False)),
                ("track_options", models.BooleanField(default=False)),
                (
                    "n_expiries",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Nearest N expiries to pull for F&O"
                    ),
                ),
                (
                    "strike_window",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="ATM +/- K strikes to pull for options"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "underlying",
                    models.ForeignKey(
                        help_text="Equity or index instrument to track",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_entries",
                        to="catalog.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "watchlist",
                "ordering": ["underlying__symbol"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("underlying",), name="uniq_watchlist_underlying"
                    )
                ],
            },
        ),
    ]
