# Generated by Django 6.0.6 on 2026-07-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="n_expiries",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="Nearest N expiries to pull for F&O"
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="strike_window",
            field=models.PositiveSmallIntegerField(
                default=20, help_text="ATM +/- K strikes to pull for options"
            ),
        ),
    ]
