# Generated by Django 6.0.6 on 2026-07-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        editable=False,
                        help_text="Deterministic natural key, e.g. 'NFO:NIFTY:OPTION:2026-01-29:22000:CE'",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("EQUITY", "Equity"),
                            ("INDEX", "Index"),
                            ("FUTURE", "Future"),
                            ("OPTION", "Option"),
                            ("CURRENCY", "Currency"),
                            ("COMMODITY", "Commodity"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("NSE", "NSE"),
                            ("BSE", "BSE"),
                            ("NFO", "NSE F&O"),
                            ("BFO", "BSE F&O"),
                            ("CDS", "Currency Derivatives"),
                            ("MCX", "Commodity"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Canonical trading symbol", max_length=64
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("segment", models.CharField(blank=True, max_length=32)),
                ("lot_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tick_size",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "isin",
                    models.CharField(
                        blank=True, help_text="Equities only", max_length=12
                    ),
                ),
                ("expiry", models.DateField(blank=True, null=True)),
                (
                    "strike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        blank=True,
                        choices=[("CE", "Call"), ("PE", "Put")],
                        default="",
                        max_length=2,
                    ),
                ),
                (
                    "is_tracked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether data-store actively syncs data for this instrument",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "data_start",
                    models.DateField(
                        blank=True, help_text="First date with stored data", null=True
                    ),
                ),
                (
                    "data_end",
                    models.DateField(
                        blank=True, help_text="Last date with stored data", null=True
                    ),
                ),
                (
                    "data_gaps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of [start, end] date ranges missing from storage",
                    ),
                ),
                (
                    "underlying",
                    models.ForeignKey(
                        blank=True,
                        help_text="Underlying instrument for futures/options",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derivatives",
                        to="catalog.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "instruments",
                "ordering": ["exchange", "symbol", "expiry", "strike"],
            },
        ),
        migrations.CreateModel(
            name="BrokerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "broker_id",
                    models.CharField(
                        help_text="e.g. 'zerodha', 'angelone'", max_length=32
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Broker-specific instrument token", max_length=64
                    ),
                ),
                (
                    "broker_symbol",
                    models.CharField(
                        help_text="Broker-specific trading symbol", max_length=128
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_tokens",
                        to="catalog.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "broker_tokens",
                "ordering": ["broker_id"],
            },
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["exchange", "symbol"], name="instruments_exchang_d616df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["instrument_type"], name="instruments_instrum_eb7192_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(fields=["expiry"], name="instruments_expiry_bb392a_idx"),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["is_tracked", "status"], name="instruments_is_trac_67ceaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokertoken",
            index=models.Index(
                fields=["broker_id", "token"], name="broker_toke_broker__083bd4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="brokertoken",
            constraint=models.UniqueConstraint(
                fields=("instrument", "broker_id"), name="uniq_instrument_broker"
            ),
        ),
    ]
