# Generated by Django 6.0.6 on 2026-07-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquityInstrument",
            fields=[],
            options={
                "verbose_name": "Equity",
                "verbose_name_plural": "Equities",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.instrument",),
        ),
        migrations.CreateModel(
            name="FutureInstrument",
            fields=[],
            options={
                "verbose_name": "Future",
                "verbose_name_plural": "Futures",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.instrument",),
        ),
        migrations.CreateModel(
            name="IndexInstrument",
            fields=[],
            options={
                "verbose_name": "Index",
                "verbose_name_plural": "Indices",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.instrument",),
        ),
        migrations.CreateModel(
            name="OptionInstrument",
            fields=[],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.instrument",),
        ),
    ]
